apiVersion: apps/v1
kind: Deployment
metadata:
  name: carbide-charts
  namespace: carbide
  labels:
    app: carbide-charts
spec:
  replicas: 3
  selector:
    matchLabels:
      app: carbide-charts
  template:
    metadata:
      labels:
        app: carbide-charts
    spec:
      containers:
      - name: carbide-charts
        image: harbor.atoy.dev/public/carbide-charts:1.0
        ports:
        - name: http
          containerPort: 80
