kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: carbide-src
  namespace: fleet-default
spec:
  repo: http://carbide-charts.carbide.svc.cluster.local/git/git-http-backend.git
  targets:
  - clusterSelector:
      matchExpressions:
      - key: carbide
        operator: notIn
        values:
        - enabled
  paths:
  - "./carbide/manifests"